table Clientes
	lineageTag: 037863c0-253f-4778-8383-49d7318c3e82

	column 'ID Cliente'
		dataType: string
		lineageTag: 6231af13-42c2-4c00-8a2d-077ce4e96b52
		summarizeBy: none
		sourceColumn: ID Cliente

		annotation SummarizationSetBy = Automatic

	column 'Nome Cliente'
		dataType: string
		lineageTag: 2415605b-2877-4944-a74e-d671629455ae
		summarizeBy: none
		sourceColumn: Nome Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 163a8da8-e3a1-4468-bf19-c03a503677a3
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: f3b4b119-dd84-496c-b7b7-344c88ae4a88
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: ccd2312e-5513-4a24-a69a-4f2e931cdd52
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Pais
		dataType: string
		lineageTag: be00dcd2-65ed-42e4-923b-908f5c1f4452
		summarizeBy: none
		sourceColumn: Pais

		annotation SummarizationSetBy = Automatic

	column Mercado
		dataType: string
		lineageTag: 5193e03d-c143-40d8-9713-a66ee2e1419c
		summarizeBy: none
		sourceColumn: Mercado

		annotation SummarizationSetBy = Automatic

	column Regiao
		dataType: string
		lineageTag: 1821a19f-628b-414b-92a1-c5722ce65a3c
		summarizeBy: none
		sourceColumn: Regiao

		annotation SummarizationSetBy = Automatic

	partition Clientes = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\admgu\OneDrive - REDEOBA\ANALYTICS\POWER BI\DSA - Power BI\3 - Modelagem, relacionamentos e DAX\1-datasets\Clientes.csv"),[Delimiter=";", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Cliente", type text}, {"Nome Cliente", type text}, {"Segmento", type text}, {"Cidade", type text}, {"Estado", type text}, {"Pais", type text}, {"Mercado", type text}, {"Regiao", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

