table Pedidos
	lineageTag: bdc55302-1dea-47ec-8e37-b024e4e638a5

	column 'ID Pedido'
		dataType: string
		lineageTag: 1315d5cd-8ec5-4e72-89d8-adf1cdc799b3
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Data Pedido'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2671aabf-3b2a-4864-9cc1-83fe1acd60ad
		summarizeBy: none
		sourceColumn: Data Pedido

		variation Variation
			isDefault
			relationship: ebd3e8da-7bc6-4a22-aa2c-0be6636b3cab
			defaultHierarchy: LocalDateTable_45fd8a7c-0a15-47b5-995a-425c0b83425c.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Envio'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9e1c9c54-38fb-4010-9206-83f459684a7d
		summarizeBy: none
		sourceColumn: Data Envio

		variation Variation
			isDefault
			relationship: 28738adf-2ddd-47c5-95c2-88816f2c743c
			defaultHierarchy: LocalDateTable_6d5e5bc9-6381-4f35-a2b6-ec94d5a539b5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Modo Envio'
		dataType: string
		lineageTag: c683b80d-c05f-41cd-bc56-5e6f259182f6
		summarizeBy: none
		sourceColumn: Modo Envio

		annotation SummarizationSetBy = Automatic

	column 'Prioridade Pedido'
		dataType: string
		lineageTag: a9a051f9-37d7-4d04-9a6f-268327e1394f
		summarizeBy: none
		sourceColumn: Prioridade Pedido

		annotation SummarizationSetBy = Automatic

	partition Pedidos = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\admgu\OneDrive - REDEOBA\ANALYTICS\POWER BI\DSA - Power BI\3 - Modelagem, relacionamentos e DAX\1-datasets\Pedidos.csv"),[Delimiter=";", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Pedido", type text}, {"Data Pedido", type date}, {"Data Envio", type date}, {"Modo Envio", type text}, {"Prioridade Pedido", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado")
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

