table Vendas
	lineageTag: 3919863c-e066-4c44-985f-f658f50cb6f6

	column Pedido
		dataType: string
		lineageTag: b6182a16-949d-475a-94e5-fb5ca2092838
		summarizeBy: none
		sourceColumn: Pedido

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 2a54320c-22cf-4ff5-aaca-6663bb85528e
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: 3b7f3df7-11a9-4e2e-96ce-101355d75f00
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column 'Valor Venda'
		dataType: double
		lineageTag: 53244864-f5b6-49ef-a6c8-d66302f34b2d
		summarizeBy: sum
		sourceColumn: Valor Venda

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Quantidade Vendida'
		dataType: int64
		formatString: 0
		lineageTag: 5d4a5a7d-2f8c-414b-8047-d055a5ca1ac2
		summarizeBy: sum
		sourceColumn: Quantidade Vendida

		annotation SummarizationSetBy = Automatic

	column 'Custo Envio'
		dataType: double
		lineageTag: e465c806-9bbc-40ce-af38-a2e5d8333c3e
		summarizeBy: sum
		sourceColumn: Custo Envio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Lucro = Vendas[Valor Venda] - Vendas[Custo Envio]
		lineageTag: fe2c8f5b-4ea8-4f7c-8bbd-e53f30bad04d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MargemLucro = ROUND(DIVIDE(Vendas[Lucro], Vendas[Valor Venda]) * 100, 2)
		lineageTag: d0c670f9-07c5-4585-ba1f-649a31b246b6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\admgu\OneDrive - REDEOBA\ANALYTICS\POWER BI\DSA - Power BI\3 - Modelagem, relacionamentos e DAX\1-datasets\Vendas.csv"),[Delimiter=";", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Pedido", type text}, {"Cliente", type text}, {"Produto", type text}, {"Valor Venda", type number}, {"Quantidade Vendida", Int64.Type}, {"Custo Envio", type number}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado"),
				    #"Duplicatas Removidas1" = Table.Distinct(#"Duplicatas Removidas")
				in
				    #"Duplicatas Removidas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

