table dim-Calendário-dinamico
	lineageTag: a9ade62b-ca5f-41e8-8baf-b37d90274604

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6534d1c-f6d2-4311-b2c8-adb780e6aa89
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 25a921f6-a799-4ac0-b2f8-a63293aa94ec
			defaultHierarchy: LocalDateTable_143df856-409f-4fb2-b277-3c82799fc36f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 6eb5894f-4886-4acc-801f-71d5823cd0de
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: a636770d-3fce-4cf6-bd32-b72d4fcba824
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: c2dd0a47-ab3d-4244-8188-ecb579069a6c
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 7772b640-3ca2-4b6c-97f8-af950317aa57
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Semana do Ano'
		dataType: int64
		formatString: 0
		lineageTag: ae4c2608-1cfe-49df-bd07-c0aef3f37baf
		summarizeBy: sum
		sourceColumn: Semana do Ano

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 7db46716-c1e0-4204-baa3-f45721c68924
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 4b1d3dea-3bf8-4534-b1f5-cc9286860b0d
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	partition dim-Calendário-dinamico = m
		mode: import
		source = ```
				let
				    dataInicial = #date(2010, 01, 01),
				    dataFinal = DateTime.Date(DateTime.LocalNow()),
				    numeroDias = Duration.Days(dataFinal - dataInicial),
				    listaDatas = List.Dates (dataInicial, numeroDias, #duration (1, 0, 0, 0)),
				    
				    #"Convertido para Tabela" = Table.FromList(listaDatas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
				    #"Semana do Ano Inserida" = Table.AddColumn(#"Trimestre Inserido", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Semana do Ano Inserida", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text)
				in
				    #"Nome do Dia Inserido"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

